# Custom section is used to store configurations that might be repetative.
# Please read YAML documentation for details on how to use substitutions and anchors.
custom:
  basic-cluster-props: &basic-cluster-props
    spark_version: "10.4.x-cpu-ml-scala2.12"

  basic-static-cluster: &basic-static-cluster
    new_cluster:
      <<: *basic-cluster-props
      num_workers: 1
      node_type_id: "Standard_E8_v3"

environments:
  default:
    workflows:
      #######################################################################################
      #   Example workflow for integration tests                                            #
      #######################################################################################
      - name: "lendingclub-rvp-test"
        tasks:
          - task_key: "main"
            spark_python_task:
                python_file: "file://tests/entrypoint.py"
                # this call supports all standard pytest arguments
                parameters: ["file:fuse://tests/integration", "--cov=lendingclub"]
            existing_cluster_id: 0807-225846-motto493
      - name: "lendingclub-rvp-train"
        tasks:
          - task_key: "main"
            python_wheel_task:
              package_name: "lendingclub_scoring"
              entry_point: "train" # take a look at the setup.py entry_points section for details on how to define an entrypoint
              parameters: ["--conf-file", "file:fuse://conf/config.json"]
            existing_cluster_id: 0807-225846-motto493
      - name: "lendingclub-rvp-abtest"
        tasks:
          - task_key: "main"
            python_wheel_task:
              package_name: "lendingclub_scoring"
              entry_point: "abtest" # take a look at the setup.py entry_points section for details on how to define an entrypoint
              parameters: ["--conf-file", "file:fuse://conf/abtest.json"]
            existing_cluster_id: 0807-225846-motto493

